.PHONY: build test vet fmt lint lint-full quality-local

build:
	GOWORK=off go build ./...

test:
	GOWORK=off go test -count=1 ./...

vet:
	GOWORK=off go vet ./...

fmt:
	GOWORK=off go fmt ./...

lint:
	GOWORK=off golangci-lint run --new ./...

lint-full:
	GOWORK=off golangci-lint run --new=false ./...

quality-local:
	GOWORK=off go build ./...
	GOWORK=off go vet ./...
	GOWORK=off golangci-lint run --new=false ./...
	GOWORK=off go test -count=1 ./...
	GOWORK=off go test -race -count=1 ./...
